// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prod (Supabase): set DIRECT_URL to the direct connection string (not the pooled one).
    // Dev (Docker):    leave DIRECT_URL unset — falls back to DATABASE_URL.
    url: (process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"])!,
  },
});
